{
 "title": "New dashboard",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Input query number in last 20 secs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(vllm_input_qps_total[20s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average time to first byte (sec)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "time_to_first_byte_seconds_sum{endpoint=\"v1/chat/completions\", job=\"host-metrics1\"} / time_to_first_byte_seconds_count",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "time_to_first_byte_seconds_sum{endpoint=\"v1/completions\", job=\"host-metrics2\"} / time_to_first_byte_seconds_count",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Average request duration (sec)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "request_duration_seconds_sum{endpoint=\"v1/chat/completions\", job=\"host-metrics1\"} / request_duration_seconds_count",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "request_duration_seconds_sum{endpoint=\"v1/completions\", job=\"host-metrics2\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Input length (token number)", "type": "text", "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 }, "options": { "content": "# 1000" } },
  {
   "title": "Output query number in last 20 secs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(vllm_output_qps_total[20s]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Average decoding throughput (tokens per sec)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 5, "y": 9 },
   "targets": [
    {
     "expr": "vllm_decoding_throughput_tokens_per_second_sum / vllm_decoding_throughput_tokens_per_second_count",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Cost for 1M tokens (dollar)",
   "type": "timeseries",
   "description": "1.5 dollar per hour",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 9 },
   "targets": [
    {
     "expr": "1000000 / (vllm_decoding_throughput_tokens_per_second_sum / vllm_decoding_throughput_tokens_per_second_count) * 1.5 / 3600",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Output length (token number)", "type": "text", "gridPos": { "h": 4, "w": 5, "x": 0, "y": 14 }, "options": { "content": "# 100" } }
 ]
}