{
 "title": "Resource monitoring",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "CPU & Disk usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU utilization %",
   "type": "timeseries",
   "description": "CPU utilization of the servers",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "cpu_usage", "legendFormat": "{{server}}" }
   ]
  },
  { "title": "GPU utilization & memory usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "GPU power (W)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "gpu_power{server=\"nature\"}",
     "legendFormat": "{{server}} GPU {{gpu_id}}"
    },
    {
     "expr": "gpu_power{server=\"heart\"}",
     "legendFormat": "{{server}} GPU {{gpu_id}}"
    }
   ]
  },
  {
   "title": "GPU temperature ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "gpu_temperature{server=\"nature\"}",
     "legendFormat": "{{server}} GPU {{gpu_id}}"
    },
    {
     "expr": "gpu_temperature{server=\"heart\"}",
     "legendFormat": "{{server}} GPU {{gpu_id}}"
    }
   ]
  },
  {
   "title": "Nature GPU utilization %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gpu_usage{server=\"nature\"}",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  {
   "title": "Nature GPU memory used ratio %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gpu_memory_used{server=\"nature\"} / gpu_memory_total{server=\"nature\"} * 100",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  {
   "title": "Heart GPU utilization %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gpu_usage{server=\"heart\"}",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  {
   "title": "Heart GPU memory used ratio %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gpu_memory_used{server=\"heart\"} / gpu_memory_total{server=\"heart\"} * 100",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  {
   "title": "Farewell GPU utilization %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gpu_usage{server=\"farewell\"}",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  {
   "title": "Farewell GPU memory used ratio %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gpu_memory_used{server=\"farewell\"} / gpu_memory_total{server=\"farewell\"} * 100",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  {
   "title": "Ziyizhang GPU utilization %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gpu_usage{server=\"ziyizhang\"}",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  {
   "title": "Ziyizhang GPU memory used ratio %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gpu_memory_used{server=\"ziyizhang\"} / gpu_memory_total{server=\"ziyizhang\"} * 100",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  { "title": "GPU usage by user", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Heatmap of GPU memory usage",
   "type": "heatmap",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "(sum by (server, gpu_id, username) (gpu_process_memory_used)) / on (server, gpu_id) group_left gpu_memory_total",
     "legendFormat": "   {{server}}:{{gpu_id}}; {{username}}"
    }
   ]
  }
 ]
}