global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
     - targets: ['localhost:9090']

  - job_name: 'host-metrics1'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:8001']

  - job_name: 'host-metrics2'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:8003']