global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
     - targets: ['localhost:9090']

  - job_name: 'Ours'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:8001']

  - job_name: 'Fireworks'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:8002']

  - job_name: 'DeepInfra'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:8003']